### ISSUE TITLE
Reworking <sourceDesc> 

### ISSUE THREAD

**Issue by lucagiovannini7** [dracor-org/engdracor#54] opened 2024-05-02 13:32 UTC
Plays have a rich `<sourceDesc>` with contains both DraCor's `<bibl>` element (referring to the digital source, i.e. Early Print) and two legacy `<biblFull>` elements from Early Print (one referring to the original printed source and the other to the digital source for Early Print itself, i.e. the Text Creation Partnership - EEBO/ECCO). See [this file](https://github.com/dracor-org/epdracor/blob/main/tei/alexander-caesar.xml) as an example. Should we simplify it to align with DraCor standards, while still keeping a reference to previous sources?

**Comment by cmil** [comment] 2024-06-09 14:22
This is a duplicate of #36, isn't it, @lucagiovannini7?

**Closed by cmil** 2024-06-09 14:22 UTC
